# root: pyproject.toml
[build-system]
requires = ["setuptools"]
build-backend = "setuptools.build_meta"

[project]
name = "bom_platform"
version = "0.1.0"

[project.scripts]
bom-gui = "gui.control_center:main"

[tool.setuptools]
packages = ["app", "gui"]
