BOM_TEMPLATE_HEADERS = [
    "PN",
    "Reference",
    "Description",
    "Manufacturer",
    "Active/Passive",
    "Function",
    "Value",
    "Tolerance P",
    "Tolerance N",
    "Price",
    "Currency",
    "Datasheet",
    "Notes",
]
